# Generated by Django 4.2.30 on 2026-08-22 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid Egyptian phone number (e.g., 01012345678).', regex='^01[0125][0-9]{8}$')]),
        ),
    ]
